version: "3.8"

services:
  gitlab:
    image: gitlab-ce
    container_name: gitlab
    restart: always
    ports:
      - "8081:80"
      - "8443:443"
      - "8022:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab

volumes:
  gitlab-config:
  gitlab-data:
  gitlab-logs:
